[workspace]
resolver = "2"
members = [
    "types",
    "config",
    "util",
    "consensus",
    # "consensus/apollo",        # TODO: migrate to libmempool-rs
    # "consensus/artemis",       # TODO: migrate to libmempool-rs
    "consensus/synchs",
    # "consensus/optsync",       # TODO: migrate to libmempool-rs
    # "examples/apollo/node",
    # "examples/apollo/client",
    # "examples/apollo/normal-client",
    # "examples/artemis/node",
    # "examples/artemis/client",
    "examples/synchs/node",
    "examples/synchs/client",
    # "examples/optsync/node",
    # "examples/optsync/client",
    "tools/genconfig",
    "stress-test",
]
exclude = [
    "consensus/apollo",
    "consensus/artemis",
    "consensus/optsync",
    "examples/apollo/node",
    "examples/apollo/client",
    "examples/apollo/normal-client",
    "examples/artemis/node",
    "examples/artemis/client",
    "examples/optsync/node",
    "examples/optsync/client",
]
