[package]
name = "node-artemis"
version = "0.1.0"
authors = ["hermitsage <dth.bht@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = { package = "config", path="../../../config"}
util = { package = "util", path="../../../util"}
consensus = { package = "consensus", path="../../../consensus"}
artemis = { package = "artemis", path="../../../consensus/artemis"}
types = { package = "types", path="../../../types"}
clap = {version = "2", features = ["yaml"]}
tokio = { version = "1.0", features = ["full"] }
futures = "0.3.8"
fnv = "1"
log="*"
simple_logger="*"

# libnet-rs transports
net-common = { package = "common", git = "https://github.com/libdist-rs/libnet-rs.git", features = ["tls"] }
tls-reliable-sender = { git = "https://github.com/libdist-rs/libnet-rs.git" }
tls-receiver = { git = "https://github.com/libdist-rs/libnet-rs.git" }
tcp-sender = { git = "https://github.com/libdist-rs/libnet-rs.git" }

# libmempool-rs + libstorage-rs
libmempool = { package = "libmempool-rs", git = "https://github.com/libdist-rs/libmempool-rs.git" }
libstorage = { package = "libstorage-rs", git = "https://github.com/libdist-rs/libstorage-rs.git" }
