[package]
name = "types"
version = "0.1.0"
authors = ["hermitsage <dth.bht@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = "1"
libcrypto = { git = "https://github.com/libdist-rs/libcrypto-rs", tag = "v0.3.2" }
anyhow = "1"
linked-hash-map = "0.5"
tokio-util = { version = "0.6", features = ["codec"] }
bytes = "1.0"
log = "0.4"
fnv = "1"

[features]
default = ["mempool"]
mempool = []
